### ISSUE TITLE
cannot use appname (type string) as type *health.StatsDSinkOptions in argument to health.NewStatsDSink

### ISSUE THREAD

**Issue by SejalAbhangrao** [utrack/gin-health#1]
I am trying to integrate it into my code however I keep getting this error - cannot use appname (type string) as type *health.StatsDSinkOptions in argument to health.NewStatsDSink. Could anyone help me figure out what's wrong?

**Comment by utrack** [comment]
`health` changed its API. Synced vs API changes in the latest commit.

Now `*health.StatsDSinkOptions` is accepted instead of `appname string`, if you were setting an appname - pass `&health.StatsDSinkOptions{Prefix:appname}` instead.
